### ISSUE TITLE
Bug in API call -  AttributeError: 'DataSource' object has no attribute 'data_type'

### ISSUE THREAD

**Issue by davidtheITguy** [embedchain/ec-admin#4]
Hi,

I think this was reported earlier in the main branch and it looked like it might have been addressed, but I am seeing this error under the back end API ` AttributeError: 'DataSource' object has no attribute 'data_type'` when running the API call ` /api/v1/admin/data_source`.

Being run from a docker instantiation via `ec start docker` for `my-app`.

Here is the traceback:
```
backend-1   | INFO:     192.168.0.60:56393 - "GET /api/v1/admin/data_sources HTTP/1.1" 500 Internal Server Error
backend-1   | ERROR:    Exception in ASGI application
backend-1   | Traceback (most recent call last):
backend-1   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
backend-1   |     result = await app(  # type: ignore[func-returns-value]
backend-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
backend-1   |     return await self.app(scope, receive, send)
backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
backend-1   |     await super().__call__(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
backend-1   |     await self.middleware_stack(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
backend-1   |     raise exc
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
backend-1   |     await self.app(scope, receive, _send)
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-1   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
backend-1   |     raise exc
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
backend-1   |     await app(scope, receive, sender)
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
backend-1   |     await route.handle(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
backend-1   |     await self.app(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
backend-1   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
backend-1   |     raise exc
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
backend-1   |     await app(scope, receive, sender)
backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 70, in app
backend-1   |     response = await func(request)
backend-1   |                ^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
backend-1   |     raise e
backend-1   |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
backend-1   |     raw_response = await run_endpoint_function(
backend-1   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
backend-1   |     return await dependant.call(**values)
backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/app/routes/admin/data_sources.py", line 22, in get_all_data_sources
backend-1   |     data_sources = ec_app.get_data_sources()
backend-1   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/usr/local/lib/python3.11/site-packages/embedchain/app.py", line 298, in get_data_sources
backend-1   |     results.append({"data_type": row.data_type, "data_value": row.data_value, "metadata": row.metadata})
backend-1   |                                  ^^^^^^^^^^^^^
backend-1   | AttributeError: 'DataSource' object has no attribute 'data_type'
```

Note I am using python 3.11 and I have also updated the pip embedchain package to what I assume is the latest (not 100% clear that the docker pull is seeing it however): `Successfully installed embedchain-0.1.93`

Thanks, -David

**Comment by deshraj** [comment]
Hey @davidtheITguy, thanks for opening the issue. This issue is already fixed in the later version of Embedchain. Just make sure to use the latest version of Embedchain python package. Thanks!
